### ISSUE TITLE
멘토링 시간

### ISSUE THREAD

**Issue by jinu12** [multicampusiot3project/info#50]

**Comment by jinu12** [comment]
- [ ] 멘토분 들 피드백

**Comment by SeungheeJeong** [comment]
1. 대형마트 사용자들 이용패턴, 연령대, 성별 등 데이트 조사 - (자료조사필요) 
- https://www.shinhancard.com/pconts/html/benefit/trendis/MOBFM501/1198849_3818.html
2. 서비스 최적 지역 선정 - 장애인유형데이터, 대형마트 위치, 인구데이터, 장애인콜택시 이용현황 등 데이터 조합 필요(자료조사완료)
- https://www.sisul.or.kr/open_content/calltaxi/community/api.jsp
3. 헬스케어 관련 서비스 - 사용자 건강상태(체중, BMI, 체지방지수, 혈압, 혈당 등 활용하여 식품 관련 서비스 추가 가능여부 판단) 
- ex) GI지수와 당부하지수(http://www.rda.go.kr/download_file/act/bookcafe069.PDF)를 이용하여 당뇨 관리가 필요한 고객에게 식품 우선추천 및 섭취 비추천 식품 안내
- ex) 제품 검색 - 칼로리 및 영양소 함량을 이용하여 다이어트에 도움이 되는 식품 추천
